# NumPy.random- Package
***


<br/>

#### Imported Packages


In [2]:
import numpy as np

## 1. Explain the overall purpose of the package.
***

NumPy is a Python library that is seen as the fundamental package for scientific computing. NumPy stands for Numerical Python and it is an extension of Numeric and Numarray. It is mostly used when working with arrays but also has functions for working in the domain of linear algebra, fourier transform and matrices. The main benefit of NumPy is that it allows for extremely fast data generation and handling. It has its own built-in data structure called an array which can store and operate on data much more efficiently. NumPy is such an important Python library that there are other libraries, such as pandas, that are built entirely on NumPy[1]. 



When dealing with simulation the ability to generate random numbers is very important and NumPy provides various routines in the submodule random (numpy.random). It uses a particular algorithm, called the Mersenne Twister, to generate pseudorandom numbers. An initial value known as the seed determines the output produced by the algorithm. For any given seed the same random output will be produced, hence the term 'pseudo'. Without knowing the seed it will be difficult for an observer to predict the output. A truly random generator would always produce an unpredictable outcome[2]. Numpy’s random number routines produce pseudorandom numbers using combinations of a BitGenerator to create sequences and a Generator to use those sequences to sample from different statistical distributions[3]. 

When conducting data analysis from time to time we may need to generate a large number of values or even an entire dataset of values and the numpy.random sub package allows us to do this.  


<br/>

## 2. Explain the use of the “Simple random data” and “Permutations” functions.
***

### Simple Random Data:

Simple random sample is a subset of a statistical population in which each member of the subset has an equal probability of being chosen[4]. It is seen as a sampling technique where every item in the population has an even chance and likelihood of being selected in the sample. It is also important to remember that most random data generated with computer programs is not seen as random in the scientific sense and are known as pseudo random. Random numbers generated through a generation algorithm are called pseudo random.

The NumPy random package contains multiple functions for generating random data such as:

##### Rand (numpy.random.rand)

The numpy.random.rand function creates an array of specified shape and fills it with random values. It generates random samples from a uniform distribution over [0, 1] so all values are equally as likely to be selected[5]. The function returns random numbers in an array of the given dimensions(the amount of rows and columns). Each time the function is ran it will give back a different selection of numbers.

**Creating a 1D array**

In [12]:
# A single array with 3 values[6]
array = np.random.rand(3)
print("1D Array filled with random values : \n", array);

1D Array filled with random values : 
 [0.22906575 0.97483451 0.4729886 ]


**Creating a 2D array**

In [13]:
# 3 arrays each with 5 values
array = np.random.rand(3, 5) 
print("2D Array filled with random values : \n", array); 

2D Array filled with random values : 
 [[0.8918712  0.20933965 0.5836829  0.31013611 0.98266243]
 [0.0719549  0.49426908 0.29125648 0.00546772 0.75559399]
 [0.53719878 0.80757579 0.4471555  0.22091266 0.90517912]]


**Creating a 3D array**

In [26]:
# 2 arrays with 3 rows and 4 values
array = np.random.rand(2, 3, 4) 
print("3D Array filled with random values : \n", array);

3D Array filled with random values : 
 [[[0.75988842 0.56996897 0.42509496 0.47507891]
  [0.95849959 0.89422597 0.0494144  0.81945015]
  [0.14971112 0.0271685  0.0172001  0.20296753]]

 [[0.00888596 0.3698368  0.86398023 0.07258518]
  [0.27596158 0.42178761 0.29287121 0.637048  ]
  [0.76348646 0.44779203 0.24849761 0.1510944 ]]]


#### Randn (numpy.random.randn)

Generates an array of a specified shape and fills the shape with random values. Numpy.random.randn function returns sample(or samples) from the "standard" normal distribution. If positive arguments are provided, randn generates an array of shape (d0, d1, …, dn), filled with random floats sampled from a univariate “normal” (Gaussian) distribution of mean 0 and variance 1 [7].

In [23]:
# 1D array
array = np.random.randn(5) 
print("1D Array filled with random values : \n", array);

1D Array filled with random values : 
 [ 0.50664156  0.75958723  1.08736026 -0.92332479  1.65755159]


In [24]:
# 2D Array    
array = np.random.randn(4, 6) 
print("2D Array filled with random values : \n", array);

2D Array filled with random values : 
 [[ 0.3575174   0.91797758  0.62015904 -0.48832602  0.74387761 -0.43600861]
 [ 0.31153168 -0.36810246 -1.33878721 -0.03944724 -0.67209666  1.15192751]
 [ 2.3298425  -0.46094981  0.56331558 -1.26043565  0.6627787   0.22856674]
 [-0.15899755 -1.01905059 -0.30057297 -0.0789243  -0.05874416  1.31311373]]


In [25]:
# 3D Array      
array = np.random.randn(2, 2 ,2) 
print("3D Array filled with random values : \n", array); 

3D Array filled with random values : 
 [[[ 0.14443886  0.04687765]
  [ 0.90209951 -1.83233517]]

 [[ 0.65182686  0.14718745]
  [ 0.9102385   1.75238156]]]


<br/>

#### Randint (numpy.random.randint)

The numpy.random.randint function returns random integers from low (inclusive) to high (exclusive) using the uniform distribution. The function also takes a size parameter. 

        Low: Sets the lowest integer to be taken from (Start). If there is no high value the low becomes the highest.
        High: Largest integer to be drawn from (End). This is optional, if excuded the default value will be 0, low. 
        Size: Refers to the output shape.
        Dtype: Set dtype of result. All dtypes are determined by their names with the default value set to 'int'[8].




In [6]:
# Create an array
# 1 will be included and 5 excluded
arr = np.random.randint(low = 1, high = 5, size = 5) 
print (arr)

[1 1 1 3 2]


In [11]:
# Generate random numbers between 0 and 20
# No high value so default set to (0, low)
arr = np.random.randint(low = 20, size = 10)
print (arr)

[ 5 18 16  4 16 16 13  7  9 17]


<br/>

#### Random_integers (numpy.random.random_integers)

The random_integers function works similar to randint, but 1 is the lowest value if the high value is omitted. This function has been deprecated and replaced by randint[9].

In [12]:
# Generate random numbers between 1 and 10
# You are told to use the randint function instead
np.random.random_integers(10)

<ipython-input-12-7cf0d8ba9091>:2: DeprecationWarning: This function is deprecated. Please call randint(1, 10 + 1) instead
  np.random.random_integers(10)


7

<br/>

#### Random_sample (numpy.random.random_sample)

Random_sample returns an array of random floats from the continuous unifrom distribution. It returns in the interval (0.0, 0.1) or just a single random float if no size values are provided [10]. Other functions such as random, sample and ranf can give the same output as random_sample. 

In [23]:
# Generate a random number
np.random.random_sample()

0.8664156598232672

In [13]:
# Generate 10 random numbers
np.random.random_sample(10)

array([0.48797723, 0.83550932, 0.30937183, 0.96582406, 0.42781763,
       0.48864244, 0.61867667, 0.74447225, 0.62200408, 0.93062535])

In [21]:
# Create 2D array
np.random.random_sample(size =(1, 5)) 


array([[0.50267754, 0.04949393, 0.08481763, 0.63193376, 0.98123391]])

In [22]:
# Create 3D array
np.random.random_sample ((3, 2, 1))

array([[[0.63535751],
        [0.5863342 ]],

       [[0.46492783],
        [0.71559493]],

       [[0.3000382 ],
        [0.32415411]]])

In [28]:
# Using Random
np.random.random(5)

array([0.09666208, 0.21574717, 0.25955884, 0.07826331, 0.74444178])

In [27]:
# Using Sample
np.random.sample(5)

array([0.63209601, 0.3923391 , 0.57509555, 0.11130881, 0.29877547])

In [29]:
# Using Ranf
np.random.ranf(5)

array([0.80565152, 0.93671337, 0.35750408, 0.43448462, 0.41949444])

<br/>

#### Choice (numpy.random.choice)


The Choice function allows you to generate a random sample from an array. Random.choice takes an array as a parameter and randomly returns one of its values, it can also be used to return multiple values. This is uselful when you want to choose multiple items from a particular list[11]. 

In [30]:
# Generate 3 random numbers between 1 and 5
np.random.choice(5, 3)

array([3, 4, 4])

In [34]:
animal = ['dog', 'cat', 'bear', 'lion', 'ape', 'bird']

# Get on random sample from list
np.random.choice(animal)

'bird'

In [35]:
# Get 3 random samples from the list
np.random.choice(animal, 3)

array(['cat', 'lion', 'ape'], dtype='<U4')

In [36]:
# Create a random array with 3 rows and 2 columns
np.random.choice(animal,(3,2))

array([['lion', 'ape'],
       ['bird', 'bear'],
       ['ape', 'ape']], dtype='<U4')

<br/>

#### Bytes (numpy.random.bytes)

The bytes function returns random bytes and you can set the lenght of the output.

In [46]:
np.random.bytes(10)

b'\xd1\xd07V\x87\x07\xaeTg\xf3'

<br/>
<br/>

### Permutations:

A permutation refers to an arrangement of elements. e.g. 3,2,1 is a permutation of 1,2,3 and vice-versa. The NumPy Random module provides two methods for this, shuffle and permutation[12].

<br/>

#### Shuffle (numpy.random.shuffle)

The shuffle function is used to modify a sequence by shuffling its contents. It changes the arrangement of elements in the array itself but the contents always remain the same. The function only shuffles along the first axis of a multi-dimensional array[13].   

In [85]:
# Shuffle a list
animal = ['dog', 'cat', 'bear', 'lion', 'ape', 'bird']

np.random.shuffle(animal)
animal

['bear', 'dog', 'cat', 'lion', 'ape', 'bird']

<br/>

#### Permutation (numpy.random.permutation)


Permutation is used to randomly permute a sequence or return a permuted range. If used on a multi-dimensional array it is only shuffled along its first index. The permutation functions returns a rearranged array but unlike shuffle it leaves the original array unchanged[14].

In [94]:
# Using Permutation
animal = ['dog', 'cat', 'bear', 'lion', 'ape', 'bird']

np.random.permutation(animal)
animal

['dog', 'cat', 'bear', 'lion', 'ape', 'bird']

<br/>
<br/>

## 3. Explain the use and purpose of at least five “Distributions” functions.
***

!!!!!!! EXPLAIN DISTRIBUTIONS !!!!!!!!!!

There are two main types of distribution, discreet and continuous.

Discreet distribution 

Continuous distribution

<br>

#### References
****

[1]. Freecodecamp. https://www.freecodecamp.org/news/the-ultimate-guide-to-the-numpy-scientific-computing-library-for-python/

[2]. Getting Started with Python Data Analysis. https://subscription.packtpub.com/book/big_data_and_business_intelligence/9781785285110/2/ch02lvl1sec16/numpy-random-numbers

[3]. NumPy.org https://numpy.org/doc/stable/reference/random/index.html

[4]. Investopedia https://www.investopedia.com/terms/s/simple-random-sample.asp

[5]. docs.scipy.org https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.random.rand.html#numpy.random.rand

[6]. geeksforgeeks.org https://www.geeksforgeeks.org/numpy-random-rand-python/
    
[7]. geeksforgeeks.org https://www.geeksforgeeks.org/numpy-random-randn-python/?ref=lbp

[8]. docs.scipy.org https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.random.randint.html

[9]. docs.scipy.org https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.random.random_integers.html#numpy.random.random_integers

[10]. docs.scipy.org https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.random.random_sample.html#numpy.random.random_sample

[11]. docs.scipy.org https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.random.choice.html#numpy.random.choice

[12]. w3schools.com https://www.w3schools.com/python/numpy_random_permutation.asp

[13]. docs.scipy.org https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.random.shuffle.html#numpy.random.shuffle

[14]. w3schools.com https://www.w3schools.com/python/numpy_random_permutation.asp







